#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require 'daemon'
require 'yaml'
require 'fetcher'

class <%=class_name%>FetcherDaemon < Daemon::Base
  
  @config = YAML.load_file("#{RAILS_ROOT}/config/<%=file_name%>_fetcher.yml")
  @config = @config[RAILS_ENV].to_options
  
  @sleep_time = @config.delete(:sleep_time)
  def self.start
    puts "Starting <%=class_name%>Fetcher"
    # Add your own receiver object below and specify fetcher subclass
    @fetcher = Fetcher::Base.new({:receiver => nil, :type => nil}.merge(@config))

    loop do
      @fetcher.fetch
      sleep(@sleep_time)
    end
  end
  
end

